#!/usr/bin/env node
/**
 * Knowledge Data Generator
 *
 * このスクリプトはmarkdownファイルをTypeScriptファイルに変換し、
 * Cloudflare Workersでfs.readFileSyncを使わずに知識データを利用できるようにします。
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// プロジェクトルートとソースディレクトリのパス
const projectRoot = join(__dirname, '..');
const knowledgeDir = join(projectRoot, 'src', 'knowledge');
const outputFile = join(knowledgeDir, 'data.ts');

// 変換対象のmarkdownファイル
const knowledgeFiles = [
  'bidding-methods.md',
  'evaluation.md',
  'glossary.md',
  'investigation-primer.md',
  'legal-constraints.md',
  'qualifications.md',
  'search-strategies.md',
  'timelines.md',
];

/**
 * 文字列をTypeScriptの文字列リテラルとしてエスケープ
 */
function escapeForTypeScript(content: string): string {
  // バッククォートをエスケープ
  return content.replace(/`/g, '\\`').replace(/\$/g, '\\$');
}

/**
 * markdownファイルを読み込んでTypeScriptコードを生成
 */
function generateKnowledgeData(): void {
  console.log('📚 Generating knowledge data...');

  const dataMap: Record<string, string> = {};

  // 各markdownファイルを読み込む
  for (const filename of knowledgeFiles) {
    const filepath = join(knowledgeDir, filename);
    try {
      const content = readFileSync(filepath, 'utf-8');
      dataMap[filename] = content;
      console.log(`  ✓ Loaded ${filename} (${content.length} bytes)`);
    } catch (error) {
      console.error(`  ✗ Failed to load ${filename}:`, error);
      process.exit(1);
    }
  }

  // TypeScriptコードを生成
  const lines: string[] = [
    '/**',
    ' * Auto-generated knowledge data',
    ' * DO NOT EDIT MANUALLY',
    ' * Generated by scripts/generate-knowledge-data.ts',
    ' */',
    '',
    '/**',
    ' * Knowledge data map: filename -> markdown content',
    ' */',
    'export const KNOWLEDGE_DATA: Record<string, string> = {',
  ];

  for (const [filename, content] of Object.entries(dataMap)) {
    const escaped = escapeForTypeScript(content);
    lines.push(`  '${filename}': \`${escaped}\`,`);
  }

  lines.push('};');
  lines.push('');

  const output = lines.join('\n');

  // ファイルに書き込む
  try {
    writeFileSync(outputFile, output, 'utf-8');
    console.log(`\n✅ Generated ${outputFile}`);
    console.log(`   Total files: ${knowledgeFiles.length}`);
    console.log(`   Total size: ${output.length} bytes`);
  } catch (error) {
    console.error('Failed to write output file:', error);
    process.exit(1);
  }
}

// スクリプト実行
generateKnowledgeData();
